# Generated by Django 4.0.2 on 2023-12-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_essayquestion_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='required',
        ),
    ]
