# Generated by Django 4.0.2 on 2023-12-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_multichoicequestion_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='choices',
            name='mcq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.multichoicequestion'),
        ),
    ]
