# Generated by Django 4.1 on 2023-12-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0006_question_essayquestion_question_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("question_img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
