# Generated by Django 5.0 on 2023-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_essayquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
