# Generated by Django 4.0.2 on 2023-12-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_essayquestion_question_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essayquestion',
            old_name='question_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='multichoicequestion',
            old_name='question_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='shortquestion',
            old_name='question_type',
            new_name='category',
        ),
    ]
