# Generated by Django 4.0.2 on 2023-12-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_essayquestion_image'),
        ('questions', '0007_rename_question_type_essayquestion_category_and_more'),
    ]

    operations = [
    ]
