# Generated by Django 4.0.2 on 2023-12-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_merge_20231227_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestion',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
